version: '3.8'
services:
  flask:
    build:
        context: .
        dockerfile: Dockerfile
    command: 'python main.py'
    ports:
        - "8001:5000" # port:hostport
    volumes:
      - .:/app
    depends_on:
      - db

  queue:
    build:
      context: .
      dockerfile: Dockerfile
    command: 'python -u consumer.py'
    depends_on:
      - db

  db:
    image: mysql:5.7.22
    environment:
      MYSQL_ROOT_PASSWORD: "root"
      MYSQL_DATABASE: "db_microservice"
      MYSQL_USER: "user"
      MYSQL_PASSWORD: "password"
    restart: always
    ports:
      - "33067:3306" # port 3306 is exposed to the outside world
    volumes:
        - .dbdata:/var/lib/mysql