"""Migration message

Revision ID: 4494ec66994d
Revises: 
Create Date: 2022-07-26 23:25:51.166971

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '4494ec66994d'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('tool',
    sa.Column('id', sa.Integer(), autoincrement=False, nullable=False),
    sa.Column('title', sa.String(length=200), nullable=True),
    sa.Column('tool_num', sa.String(length=200), nullable=True),
    sa.Column('raw_image', sa.String(length=200), nullable=True),
    sa.Column('processed_image', sa.String(length=200), nullable=True),
    sa.Column('wear_area', sa.Float(), nullable=True),
    sa.Column('wear_length', sa.Float(), nullable=True),
    sa.Column('vb_max', sa.Float(), nullable=True),
    sa.Column('vb_mean', sa.Float(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('user',
    sa.Column('id', sa.Integer(), autoincrement=False, nullable=False),
    sa.Column('username', sa.String(length=200), nullable=True),
    sa.Column('password', sa.String(length=200), nullable=True),
    sa.Column('email', sa.String(length=200), nullable=True),
    sa.Column('date', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('user')
    op.drop_table('tool')
    # ### end Alembic commands ###
